import { NextRequest, NextResponse } from 'next/server';
import dbConnect from '@/lib/db/mongodb';
import License from '@/models/License';
import ActivityLog from '@/models/ActivityLog';
import { getAuthUser } from '@/lib/auth-server';
import {
  generateLicenseKey,
  validateLicenseKeyFormat,
  getLicenseTypeFromKey,
  calculateExpirationDate,
} from '@/lib/license';

export async function POST(req: NextRequest) {
  try {
    await dbConnect();
    
    const authUser = await getAuthUser();
    if (!authUser) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Only admins can regenerate licenses
    if (authUser.role !== 'super_admin') {
      return NextResponse.json({ error: 'Forbidden - Admin access required' }, { status: 403 });
    }

    const body = await req.json();
    const { 
      licenseIds,
      reason,
      newExpirationDate,
      features,
      maxUsers,
      maxBranches,
      notifyUsers = false,
    } = body;

    // Validate input
    if (!licenseIds || !Array.isArray(licenseIds) || licenseIds.length === 0) {
      return NextResponse.json({ error: 'License IDs are required' }, { status: 400 });
    }

    const results: {
      success: Array<{ licenseId: string; previousKey: string; newKey: string; businessName: string; email: string }>;
      failed: Array<{ licenseId: string; error: string }>;
    } = {
      success: [],
      failed: [],
    };

    // Process each license
    for (const licenseId of licenseIds) {
      try {
        const license = await License.findById(licenseId);
        
        if (!license) {
          results.failed.push({ licenseId, error: 'License not found' });
          continue;
        }

        // Store previous key for audit
        const previousKey = license.licenseKey;

        // Generate new license key
        const newLicenseKey = generateLicenseKey(license.licenseType, license.businessName);
        
        // Validate generated license key
        if (!validateLicenseKeyFormat(newLicenseKey)) {
          results.failed.push({ licenseId, error: 'Generated license key has invalid format' });
          continue;
        }
        
        // Validate license type from key matches
        const keyType = getLicenseTypeFromKey(newLicenseKey);
        if (keyType !== license.licenseType) {
          results.failed.push({ licenseId, error: 'Generated license key type does not match license type' });
          continue;
        }
        
        // Check for duplicate license key
        const existingLicense = await License.findOne({ licenseKey: newLicenseKey });
        if (existingLicense) {
          results.failed.push({ licenseId, error: 'Generated license key already exists. Please try again.' });
          continue;
        }

        // Calculate new expiration date if provided
        let expirationDate = license.expirationDate;
        if (newExpirationDate) {
          expirationDate = new Date(newExpirationDate);
        }

        // Update features if provided
        const updatedFeatures = features || license.features;
        
        // Update max users/branches if provided
        const updatedMaxUsers = maxUsers || license.maxUsers;
        const updatedMaxBranches = maxBranches || license.maxBranches;

        // Initialize regeneration history if not present
        if (!license.regenerationHistory) {
          license.regenerationHistory = [];
        }

        // Add to regeneration history
        license.regenerationHistory.push({
          date: new Date(),
          previousKey,
          newKey: newLicenseKey,
          reason: reason || 'Regenerated by administrator',
          performedBy: authUser.email,
          expirationDate,
          features: updatedFeatures,
          maxUsers: updatedMaxUsers,
          maxBranches: updatedMaxBranches,
        });

        // Update license with new key and settings
        license.previousLicenseKey = previousKey;
        license.licenseKey = newLicenseKey;
        license.regeneratedAt = new Date();
        license.regeneratedBy = authUser.email;
        license.expirationDate = expirationDate;
        license.features = updatedFeatures;
        license.maxUsers = updatedMaxUsers;
        license.maxBranches = updatedMaxBranches;

        // If license was expired, reactivate it
        if (license.status === 'expired' && new Date(expirationDate) > new Date()) {
          license.status = 'active';
        }

        await license.save();

        results.success.push({
          licenseId,
          previousKey,
          newKey: newLicenseKey,
          businessName: license.businessName,
          email: license.email,
        });

        // Create activity log entry
        try {
          await ActivityLog.create({
            user: authUser.userId,
            userName: authUser.name,
            action: 'license_regenerated',
            module: 'licenses',
            description: `Regenerated license key for ${license.businessName} (${license.email})`,
            metadata: {
              licenseId: license._id,
              previousKey,
              newKey: newLicenseKey,
              reason: reason || 'Regenerated by administrator',
              businessName: license.businessName,
              email: license.email,
              licenseType: license.licenseType,
              expirationDate,
              features: updatedFeatures,
              maxUsers: updatedMaxUsers,
              maxBranches: updatedMaxBranches,
            },
            branch: authUser.branch,
          });
        } catch (logError) {
          console.error('Failed to create activity log for license regeneration:', logError);
        }

        // Log activity to console
        console.log(`[LICENSE REGENERATION] Admin ${authUser.email} regenerated license for ${license.businessName} (${license.email}). Previous: ${previousKey}, New: ${newLicenseKey}`);

      } catch (error) {
        console.error(`Error regenerating license ${licenseId}:`, error);
        results.failed.push({ licenseId, error: 'Failed to regenerate license' });
      }
    }

    // Prepare response message
    let message = '';
    if (results.success.length > 0 && results.failed.length === 0) {
      message = `Successfully regenerated ${results.success.length} license(s)`;
    } else if (results.success.length > 0 && results.failed.length > 0) {
      message = `Regenerated ${results.success.length} license(s), ${results.failed.length} failed`;
    } else {
      message = `Failed to regenerate all ${results.failed.length} license(s)`;
    }

    return NextResponse.json({
      message,
      results,
      notifyUsers,
    });
  } catch (error) {
    console.error('Error in license regeneration:', error);
    return NextResponse.json({ error: 'Failed to process regeneration request' }, { status: 500 });
  }
}

// GET endpoint to retrieve regeneration history for a specific license
export async function GET(req: NextRequest) {
  try {
    await dbConnect();
    
    const authUser = await getAuthUser();
    if (!authUser) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Only admins can view regeneration history
    if (authUser.role !== 'super_admin') {
      return NextResponse.json({ error: 'Forbidden - Admin access required' }, { status: 403 });
    }

    const { searchParams } = new URL(req.url);
    const licenseId = searchParams.get('licenseId');

    if (!licenseId) {
      return NextResponse.json({ error: 'License ID is required' }, { status: 400 });
    }

    const license = await License.findById(licenseId).select('regenerationHistory previousLicenseKey regeneratedAt regeneratedBy');
    
    if (!license) {
      return NextResponse.json({ error: 'License not found' }, { status: 404 });
    }

    return NextResponse.json({
      licenseId,
      previousLicenseKey: license.previousLicenseKey,
      regeneratedAt: license.regeneratedAt,
      regeneratedBy: license.regeneratedBy,
      regenerationHistory: license.regenerationHistory || [],
    });
  } catch (error) {
    console.error('Error fetching regeneration history:', error);
    return NextResponse.json({ error: 'Failed to fetch regeneration history' }, { status: 500 });
  }
}
