import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import { User, Category, Supplier, Product, Customer, Sale, Settings } from '../src/models';

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/nairobi-pos';

async function seedDatabase(clearFirst = false) {
  console.log('Connecting to MongoDB...');
  await mongoose.connect(MONGODB_URI);
  console.log('Connected to MongoDB');

  if (clearFirst) {
    console.log('Clearing existing data...');
    await User.deleteMany({});
    await Category.deleteMany({});
    await Supplier.deleteMany({});
    await Product.deleteMany({});
    await Customer.deleteMany({});
    await Sale.deleteMany({});
    await Settings.deleteMany({});
  }

  // Create Users
  console.log('Creating users...');
  const adminPassword = await bcrypt.hash('admin123', 10);
  const superAdminPassword = await bcrypt.hash('superadmin123', 10);
  const managerPassword = await bcrypt.hash('manager123', 10);
  const cashierPassword = await bcrypt.hash('cashier123', 10);

  const users = await User.insertMany([
    {
      name: 'Super Administrator',
      email: 'superadmin@pos.com',
      phone: '+254700000000',
      password: superAdminPassword,
      role: 'super_admin',
      isActive: true,
    },
    {
      name: 'System Administrator',
      email: 'admin@pos.com',
      phone: '+254700000001',
      password: adminPassword,
      role: 'admin',
      isActive: true,
    },
    {
      name: 'Store Manager',
      email: 'manager@pos.com',
      phone: '+254700000002',
      password: managerPassword,
      role: 'manager',
      isActive: true,
    },
    {
      name: 'John Cashier',
      email: 'cashier@pos.com',
      phone: '+254700000003',
      password: cashierPassword,
      role: 'cashier',
      isActive: true,
    },
    {
      name: 'Jane Stock Manager',
      email: 'stock@pos.com',
      phone: '+254700000004',
      password: cashierPassword,
      role: 'stock_manager',
      isActive: true,
    },
  ]);
  console.log(`Created ${users.length} users`);

  // Create Categories
  console.log('Creating categories...');
  const categories = await Category.insertMany([
    { name: 'Electronics', code: 'ELEC', description: 'Electronic devices and accessories', isActive: true },
    { name: 'Food & Beverages', code: 'FOOD', description: 'Food items and drinks', isActive: true },
    { name: 'Household', code: 'HOUSE', description: 'Household items', isActive: true },
    { name: 'Clothing', code: 'CLOTH', description: 'Apparel and fashion', isActive: true },
    { name: 'Health & Beauty', code: 'HEALTH', description: 'Health and beauty products', isActive: true },
    { name: 'Office Supplies', code: 'OFFICE', description: 'Office and school supplies', isActive: true },
    { name: 'Sports', code: 'SPORT', description: 'Sports equipment and accessories', isActive: true },
    { name: 'Mobile Accessories', code: 'MOBILE', description: 'Phone and tablet accessories', isActive: true },
  ]);
  console.log(`Created ${categories.length} categories`);

  // Create Suppliers
  console.log('Creating suppliers...');
  const suppliers = await Supplier.insertMany([
    {
      name: 'Kenya Electronics Ltd',
      code: 'SUP001',
      email: 'orders@kenyaelectronics.co.ke',
      phone: '+254700100001',
      address: 'Industrial Area, Nairobi',
      businessName: 'Kenya Electronics Limited',
      kraPin: 'P0512345678A',
      balance: 0,
      totalPurchases: 0,
      isActive: true,
    },
    {
      name: 'East Africa Food Distributors',
      code: 'SUP002',
      email: 'sales@eafood.co.ke',
      phone: '+254700100002',
      address: 'Mombasa Road, Nairobi',
      businessName: 'East Africa Food Distributors Ltd',
      kraPin: 'P0512345678B',
      balance: 0,
      totalPurchases: 0,
      isActive: true,
    },
    {
      name: 'Premier Household Suppliers',
      code: 'SUP003',
      email: 'info@premierhousehold.co.ke',
      phone: '+254700100003',
      address: 'Westlands, Nairobi',
      businessName: 'Premier Household Suppliers Ltd',
      kraPin: 'P0512345678C',
      balance: 0,
      totalPurchases: 0,
      isActive: true,
    },
    {
      name: 'Fashion Forward Kenya',
      code: 'SUP004',
      email: 'orders@fashionforward.co.ke',
      phone: '+254700100004',
      address: 'Kenyatta Avenue, Nairobi',
      businessName: 'Fashion Forward Kenya Ltd',
      kraPin: 'P0512345678D',
      balance: 0,
      totalPurchases: 0,
      isActive: true,
    },
    {
      name: 'Health Plus Pharmaceuticals',
      code: 'SUP005',
      email: 'supplies@healthplus.co.ke',
      phone: '+254700100005',
      address: 'Ngong Road, Nairobi',
      businessName: 'Health Plus Pharmaceuticals Ltd',
      kraPin: 'P0512345678E',
      balance: 0,
      totalPurchases: 0,
      isActive: true,
    },
  ]);
  console.log(`Created ${suppliers.length} suppliers`);

  // Create Products
  console.log('Creating products...');
  const products = await Product.insertMany([
    // Electronics
    {
      name: 'Samsung Galaxy A14',
      sku: 'ELEC001',
      barcode: '1234567890123',
      description: 'Samsung Galaxy A14 smartphone',
      category: categories[0]._id,
      brand: 'Samsung',
      retailPrice: 18999,
      wholesalePrice: 17000,
      distributorPrice: 15500,
      costPrice: 15000,
      stockQuantity: 50,
      lowStockThreshold: 10,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[0]._id,
    },
    {
      name: 'Sony WH-1000XM5 Headphones',
      sku: 'ELEC002',
      barcode: '1234567890124',
      description: 'Wireless noise cancelling headphones',
      category: categories[0]._id,
      brand: 'Sony',
      retailPrice: 32999,
      wholesalePrice: 30000,
      distributorPrice: 28000,
      costPrice: 27000,
      stockQuantity: 25,
      lowStockThreshold: 5,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[0]._id,
    },
    {
      name: 'HP Laptop 15s',
      sku: 'ELEC003',
      barcode: '1234567890125',
      description: 'HP 15s laptop with Intel Core i5',
      category: categories[0]._id,
      brand: 'HP',
      retailPrice: 74999,
      wholesalePrice: 70000,
      distributorPrice: 65000,
      costPrice: 63000,
      stockQuantity: 15,
      lowStockThreshold: 3,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[0]._id,
    },
    // Food & Beverages
    {
      name: 'Nescafe Coffee 500g',
      sku: 'FOOD001',
      barcode: '2234567890123',
      description: 'Instant coffee powder',
      category: categories[1]._id,
      brand: 'Nescafe',
      retailPrice: 1299,
      wholesalePrice: 1150,
      distributorPrice: 1050,
      costPrice: 1000,
      stockQuantity: 200,
      lowStockThreshold: 50,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[1]._id,
    },
    {
      name: 'Milo Pack 1kg',
      sku: 'FOOD002',
      barcode: '2234567890124',
      description: 'Milo chocolate malt drink',
      category: categories[1]._id,
      brand: 'Nestle',
      retailPrice: 899,
      wholesalePrice: 800,
      distributorPrice: 750,
      costPrice: 700,
      stockQuantity: 150,
      lowStockThreshold: 30,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[1]._id,
    },
    {
      name: 'Coca-Cola 500ml (24 pack)',
      sku: 'FOOD003',
      barcode: '2234567890125',
      description: 'Coca-Cola soft drink',
      category: categories[1]._id,
      brand: 'Coca-Cola',
      retailPrice: 720,
      wholesalePrice: 650,
      distributorPrice: 600,
      costPrice: 550,
      stockQuantity: 100,
      lowStockThreshold: 20,
      unit: 'pack',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[1]._id,
    },
    // Household
    {
      name: 'Omo Detergent 2kg',
      sku: 'HOUSE001',
      barcode: '3234567890123',
      description: 'Omo laundry detergent powder',
      category: categories[2]._id,
      brand: 'Omo',
      retailPrice: 699,
      wholesalePrice: 620,
      distributorPrice: 580,
      costPrice: 550,
      stockQuantity: 180,
      lowStockThreshold: 40,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[2]._id,
    },
    {
      name: 'Tide Detergent 1kg',
      sku: 'HOUSE002',
      barcode: '3234567890124',
      description: 'Tide laundry detergent',
      category: categories[2]._id,
      brand: 'Tide',
      retailPrice: 499,
      wholesalePrice: 440,
      distributorPrice: 400,
      costPrice: 380,
      stockQuantity: 200,
      lowStockThreshold: 50,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[2]._id,
    },
    {
      name: 'Reynolds Ballpen (12 pack)',
      sku: 'OFFICE001',
      barcode: '6234567890123',
      description: 'Blue ballpoint pens',
      category: categories[5]._id,
      brand: 'Reynolds',
      retailPrice: 180,
      wholesalePrice: 150,
      distributorPrice: 130,
      costPrice: 120,
      stockQuantity: 500,
      lowStockThreshold: 100,
      unit: 'pack',
      isActive: true,
      isTrackStock: true,
    },
    {
      name: 'A4 Paper (500 sheets)',
      sku: 'OFFICE002',
      barcode: '6234567890124',
      description: 'White A4 printing paper',
      category: categories[5]._id,
      brand: 'Double A',
      retailPrice: 450,
      wholesalePrice: 400,
      distributorPrice: 370,
      costPrice: 350,
      stockQuantity: 300,
      lowStockThreshold: 50,
      unit: 'ream',
      isActive: true,
      isTrackStock: true,
    },
    // Mobile Accessories
    {
      name: 'iPhone Charger Cable',
      sku: 'MOBILE001',
      barcode: '8234567890123',
      description: 'Lightning cable 1m',
      category: categories[7]._id,
      brand: 'Apple',
      retailPrice: 1499,
      wholesalePrice: 1300,
      distributorPrice: 1150,
      costPrice: 1100,
      stockQuantity: 80,
      lowStockThreshold: 20,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[0]._id,
    },
    {
      name: 'Samsung Fast Charger',
      sku: 'MOBILE002',
      barcode: '8234567890124',
      description: '25W USB-C fast charger',
      category: categories[7]._id,
      brand: 'Samsung',
      retailPrice: 2499,
      wholesalePrice: 2200,
      distributorPrice: 2000,
      costPrice: 1900,
      stockQuantity: 60,
      lowStockThreshold: 15,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[0]._id,
    },
    // Health & Beauty
    {
      name: 'Dove Soap 100g',
      sku: 'HEALTH001',
      barcode: '5234567890123',
      description: 'Dove beauty bar',
      category: categories[4]._id,
      brand: 'Dove',
      retailPrice: 150,
      wholesalePrice: 130,
      distributorPrice: 115,
      costPrice: 110,
      stockQuantity: 400,
      lowStockThreshold: 100,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[4]._id,
    },
    {
      name: 'Vaseline Body Lotion 400ml',
      sku: 'HEALTH002',
      barcode: '5234567890124',
      description: 'Vaseline Intensive Care lotion',
      category: categories[4]._id,
      brand: 'Vaseline',
      retailPrice: 599,
      wholesalePrice: 530,
      distributorPrice: 480,
      costPrice: 460,
      stockQuantity: 120,
      lowStockThreshold: 30,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[4]._id,
    },
    // Clothing
    {
      name: 'Men\'s Cotton T-Shirt',
      sku: 'CLOTH001',
      barcode: '4234567890123',
      description: '100% cotton plain t-shirt',
      category: categories[3]._id,
      brand: 'Generic',
      retailPrice: 899,
      wholesalePrice: 780,
      distributorPrice: 700,
      costPrice: 680,
      stockQuantity: 75,
      lowStockThreshold: 20,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
      supplier: suppliers[3]._id,
    },
    // Sports
    {
      name: 'Nike Football',
      sku: 'SPORT001',
      barcode: '7234567890123',
      description: 'Nike Merlin football',
      category: categories[6]._id,
      brand: 'Nike',
      retailPrice: 2499,
      wholesalePrice: 2200,
      distributorPrice: 2000,
      costPrice: 1900,
      stockQuantity: 30,
      lowStockThreshold: 10,
      unit: 'piece',
      isActive: true,
      isTrackStock: true,
    },
  ]);
  console.log(`Created ${products.length} products`);

  // Create Customers
  console.log('Creating customers...');
  const customers = await Customer.insertMany([
    {
      name: 'John Doe',
      email: 'john.doe@email.com',
      phone: '+254711111111',
      address: 'Nairobi, Kenya',
      creditBalance: 0,
      loyaltyPoints: 500,
      customerType: 'retail',
      isActive: true,
      totalPurchases: 5,
      totalSpent: 25000,
    },
    {
      name: 'Jane Smith',
      email: 'jane.smith@email.com',
      phone: '+254722222222',
      address: 'Kisumu, Kenya',
      creditBalance: 0,
      loyaltyPoints: 1200,
      customerType: 'wholesale',
      businessName: 'Smith Enterprises',
      kraPin: 'P0599999999A',
      creditLimit: 100000,
      isActive: true,
      totalPurchases: 25,
      totalSpent: 450000,
    },
    {
      name: 'Moses Ochieng',
      email: 'moses.ochieng@email.com',
      phone: '+254733333333',
      address: 'Mombasa, Kenya',
      creditBalance: 5000,
      loyaltyPoints: 800,
      customerType: 'retail',
      isActive: true,
      totalPurchases: 12,
      totalSpent: 89000,
    },
    {
      name: 'Wema Supermarket',
      email: 'orders@wemasupermarket.co.ke',
      phone: '+254744444444',
      address: 'Eldoret, Kenya',
      creditBalance: 0,
      loyaltyPoints: 5000,
      customerType: 'distributor',
      businessName: 'Wema Supermarket Ltd',
      kraPin: 'P0588888888B',
      creditLimit: 500000,
      isActive: true,
      totalPurchases: 100,
      totalSpent: 2500000,
    },
    {
      name: 'Grace Atieno',
      email: 'grace.atieno@email.com',
      phone: '+254755555555',
      address: 'Nairobi, Kenya',
      creditBalance: 0,
      loyaltyPoints: 300,
      customerType: 'retail',
      isActive: true,
      totalPurchases: 3,
      totalSpent: 15000,
    },
  ]);
  console.log(`Created ${customers.length} customers`);

  // Create Sales
  console.log('Creating sales...');
  const today = new Date();
  const sales = await Sale.insertMany([
    {
      invoiceNumber: 'INV00001',
      customer: customers[0]._id,
      customerName: customers[0].name,
      customerPhone: customers[0].phone,
      branch: new mongoose.Types.ObjectId(),
      cashier: users[2]._id,
      cashierName: users[2].name,
      items: [
        {
          product: products[0]._id,
          productName: products[0].name,
          sku: products[0].sku,
          quantity: 1,
          unitPrice: products[0].retailPrice,
          discount: 0,
          tax: products[0].retailPrice * 0.16,
          total: products[0].retailPrice * 1.16,
          costPrice: products[0].costPrice,
        },
        {
          product: products[12]._id,
          productName: products[12].name,
          sku: products[12].sku,
          quantity: 2,
          unitPrice: products[12].retailPrice,
          discount: 0,
          tax: products[12].retailPrice * 2 * 0.16,
          total: products[12].retailPrice * 2 * 1.16,
          costPrice: products[12].costPrice,
        },
      ],
      subtotal: products[0].retailPrice + products[12].retailPrice * 2,
      discount: 0,
      discountAmount: 0,
      tax: (products[0].retailPrice + products[12].retailPrice * 2) * 0.16,
      taxRate: 16,
      total: (products[0].retailPrice + products[12].retailPrice * 2) * 1.16,
      paymentMethod: 'cash',
      amountPaid: 25000,
      change: 25000 - (products[0].retailPrice + products[12].retailPrice * 2) * 1.16,
      status: 'completed',
      profit: (products[0].retailPrice - products[0].costPrice) + (products[12].retailPrice - products[12].costPrice) * 2,
      saleDate: new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      invoiceNumber: 'INV00002',
      customer: customers[1]._id,
      customerName: customers[1].name,
      customerPhone: customers[1].phone,
      branch: new mongoose.Types.ObjectId(),
      cashier: users[2]._id,
      cashierName: users[2].name,
      items: [
        {
          product: products[3]._id,
          productName: products[3].name,
          sku: products[3].sku,
          quantity: 50,
          unitPrice: products[3].wholesalePrice,
          discount: 5,
          discountType: 'percentage',
          tax: 0,
          total: products[3].wholesalePrice * 50 * 0.95,
          costPrice: products[3].costPrice,
        },
        {
          product: products[4]._id,
          productName: products[4].name,
          sku: products[4].sku,
          quantity: 30,
          unitPrice: products[4].wholesalePrice,
          discount: 5,
          discountType: 'percentage',
          tax: 0,
          total: products[4].wholesalePrice * 30 * 0.95,
          costPrice: products[4].costPrice,
        },
      ],
      subtotal: products[3].wholesalePrice * 50 + products[4].wholesalePrice * 30,
      discount: 5,
      discountType: 'percentage',
      discountAmount: (products[3].wholesalePrice * 50 + products[4].wholesalePrice * 30) * 0.05,
      tax: 0,
      taxRate: 16,
      total: (products[3].wholesalePrice * 50 + products[4].wholesalePrice * 30) * 0.95,
      paymentMethod: 'mpesa',
      paymentDetails: [
        {
          amount: (products[3].wholesalePrice * 50 + products[4].wholesalePrice * 30) * 0.95,
          method: 'mpesa',
          reference: 'MP123456789',
        },
      ],
      amountPaid: (products[3].wholesalePrice * 50 + products[4].wholesalePrice * 30) * 0.95,
      change: 0,
      status: 'completed',
      profit: (products[3].wholesalePrice - products[3].costPrice) * 50 + (products[4].wholesalePrice - products[4].costPrice) * 30,
      saleDate: new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000),
    },
    {
      invoiceNumber: 'INV00003',
      branch: new mongoose.Types.ObjectId(),
      cashier: users[2]._id,
      cashierName: users[2].name,
      items: [
        {
          product: products[6]._id,
          productName: products[6].name,
          sku: products[6].sku,
          quantity: 3,
          unitPrice: products[6].retailPrice,
          discount: 0,
          tax: products[6].retailPrice * 3 * 0.16,
          total: products[6].retailPrice * 3 * 1.16,
          costPrice: products[6].costPrice,
        },
      ],
      subtotal: products[6].retailPrice * 3,
      discount: 0,
      discountAmount: 0,
      tax: products[6].retailPrice * 3 * 0.16,
      taxRate: 16,
      total: products[6].retailPrice * 3 * 1.16,
      paymentMethod: 'cash',
      amountPaid: 3000,
      change: 3000 - products[6].retailPrice * 3 * 1.16,
      status: 'completed',
      profit: (products[6].retailPrice - products[6].costPrice) * 3,
      saleDate: new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000),
    },
    {
      invoiceNumber: 'INV00004',
      customer: customers[3]._id,
      customerName: customers[3].name,
      customerPhone: customers[3].phone,
      branch: new mongoose.Types.ObjectId(),
      cashier: users[2]._id,
      cashierName: users[2].name,
      items: [
        {
          product: products[8]._id,
          productName: products[8].name,
          sku: products[8].sku,
          quantity: 100,
          unitPrice: products[8].wholesalePrice,
          discount: 10,
          discountType: 'percentage',
          tax: 0,
          total: products[8].wholesalePrice * 100 * 0.9,
          costPrice: products[8].costPrice,
        },
        {
          product: products[9]._id,
          productName: products[9].name,
          sku: products[9].sku,
          quantity: 200,
          unitPrice: products[9].wholesalePrice,
          discount: 10,
          discountType: 'percentage',
          tax: 0,
          total: products[9].wholesalePrice * 200 * 0.9,
          costPrice: products[9].costPrice,
        },
      ],
      subtotal: products[8].wholesalePrice * 100 + products[9].wholesalePrice * 200,
      discount: 10,
      discountType: 'percentage',
      discountAmount: (products[8].wholesalePrice * 100 + products[9].wholesalePrice * 200) * 0.1,
      tax: 0,
      taxRate: 16,
      total: (products[8].wholesalePrice * 100 + products[9].wholesalePrice * 200) * 0.9,
      paymentMethod: 'credit',
      amountPaid: 0,
      change: 0,
      status: 'completed',
      profit: (products[8].wholesalePrice - products[8].costPrice) * 100 + (products[9].wholesalePrice - products[9].costPrice) * 200,
      saleDate: new Date(today.getTime() - 3 * 24 * 60 * 60 * 1000),
    },
    {
      invoiceNumber: 'INV00005',
      branch: new mongoose.Types.ObjectId(),
      cashier: users[2]._id,
      cashierName: users[2].name,
      items: [
        {
          product: products[10]._id,
          productName: products[10].name,
          sku: products[10].sku,
          quantity: 2,
          unitPrice: products[10].retailPrice,
          discount: 10,
          discountType: 'fixed',
          tax: (products[10].retailPrice - 10) * 0.16,
          total: (products[10].retailPrice - 10) * 1.16,
          costPrice: products[10].costPrice,
        },
      ],
      subtotal: products[10].retailPrice - 10,
      discount: 10,
      discountType: 'fixed',
      discountAmount: 10,
      tax: (products[10].retailPrice - 10) * 0.16,
      taxRate: 16,
      total: (products[10].retailPrice - 10) * 1.16,
      paymentMethod: 'card',
      paymentDetails: [
        {
          amount: (products[10].retailPrice - 10) * 1.16,
          method: 'card',
          reference: 'CARD123456',
        },
      ],
      amountPaid: (products[10].retailPrice - 10) * 1.16,
      change: 0,
      status: 'completed',
      profit: (products[10].retailPrice - 10 - products[10].costPrice),
      saleDate: today,
    },
  ]);
  console.log(`Created ${sales.length} sales`);

  // Create Settings
  console.log('Creating settings...');
  const settings = await Settings.create({
    businessName: 'Nairobi POS',
    businessTagline: 'Your One-Stop Shop',
    phone: '+254700000000',
    email: 'info@nairobipos.co.ke',
    address: 'Nairobi, Kenya',
    kraPin: 'P0512345678Z',
    taxRate: 16,
    taxName: 'VAT',
    enableTax: true,
    receiptHeader: 'Welcome to Nairobi POS!',
    receiptFooter: 'Thank you for shopping with us!',
    showLogoOnReceipt: true,
    invoicePrefix: 'INV',
    invoiceNumber: 6,
    defaultPaymentMethod: 'cash',
    requireCustomerForSale: false,
    allowNegativeStock: false,
    lowStockAlert: true,
    allowMultiBranch: false,
  });
  console.log('Created settings');

  console.log('\\n=== Database seeded successfully! ===');
  console.log('\\nTest Accounts:');
  console.log('  Admin:    admin@pos.com    / admin123');
  console.log('  Manager:  manager@pos.com  / manager123');
  console.log('  Cashier:  cashier@pos.com  / cashier123');
  console.log('  Stock:    stock@pos.com     / cashier123');
  console.log('\\nSample Data:');
  console.log(`  - ${users.length} users`);
  console.log(`  - ${categories.length} categories`);
  console.log(`  - ${suppliers.length} suppliers`);
  console.log(`  - ${products.length} products`);
  console.log(`  - ${customers.length} customers`);
  console.log(`  - ${sales.length} sales`);

  await mongoose.disconnect();
  console.log('\\nDisconnected from MongoDB');
}

const args = process.argv.slice(2);
const clearFirst = args.includes('--clear');

seedDatabase(clearFirst).catch(console.error);
